apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: default
data:
  users.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <users>
            <default>
                <password></password>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <profile>default</profile>
                <quota>default</quota>
            </default>
        </users>
    </clickhouse>