apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: clickhouse
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - containerPort: 8123
        - containerPort: 9000
        volumeMounts:
        - name: clickhouse-config
          mountPath: /etc/clickhouse-server/users.d/
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
      volumes:
      - name: clickhouse-config
        configMap:
          name: clickhouse-config