apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-s3-refresh
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-s3-refresh
  template:
    metadata:
      labels:
        app: clickhouse-s3-refresh
    spec:
      containers:
      - name: clickhouse-client
        image: clickhouse/clickhouse-client:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            clickhouse-client --host=clickhouse --query="
            -- Drop and recreate the S3 table to force refresh
            DROP TABLE IF EXISTS transactions.s3_transactions;
            
            CREATE TABLE transactions.s3_transactions (
              transaction_id String,
              account_id String,
              transaction_type String,
              amount Float64,
              currency String,
              merchant_name String,
              category String,
              status String,
              balance_after Float64,
              location String,
              transaction_time String,
              transaction_date Date
            ) ENGINE = S3('https://prsv-vpb-hackathon-transaction-data-processed.s3.ap-southeast-1.amazonaws.com/transaction_date=*/part-*.snappy.parquet', 
              'Parquet', 
              'transaction_date Date');
              
            -- Insert new data
            INSERT INTO transactions.daily_transactions
            SELECT
              transaction_id,
              account_id,
              transaction_type,
              amount,
              currency,
              merchant_name,
              category,
              status,
              balance_after,
              location,
              transaction_time,
              transaction_date
            FROM transactions.s3_transactions
            WHERE (transaction_id, account_id) NOT IN (
              SELECT transaction_id, account_id FROM transactions.daily_transactions
            );"
            
            echo "$(date): Refreshed S3 data"
            sleep 5
          done
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi