apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: api
      containers:
      - name: api-service
        image: 955228589631.dkr.ecr.ap-southeast-1.amazonaws.com/vpbh-bigdata-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: CLICKHOUSE_URL
          value: "clickhouse://clickhouse-service:9000"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi